#!/usr/bin/env python
from py_rhyme.visit import VisItAPI as Vis
from py_rhyme.visit.helpers.script import InlineCombination
import argparse


def main():
    parser = argparse.ArgumentParser( description='Slice plot of a given Rhyme output')

    parser.add_argument('chombo_path', help='Path to a Rhyme chombo file', type=str)

    parser.add_argument('-v', '--var', help='Plotting variable', type=str, default='rho')
    parser.add_argument('-s', '--scaling', help='Pseudocolor plot scaling', choices=['linear', 'log'], type=str, default='linear')
    parser.add_argument('--min', help='Pseudocolor minimum value', type=float, default=None)
    parser.add_argument('--max', help='Pseudocolor maximum value', type=float, default=None)
    parser.add_argument('-c', '--colortable', help='Pseudocolor colortable', type=str, default='RdYlBu')
    parser.add_argument('-i', '--invert', help='Inverting pseudocolor colortable', action='store_false')
    parser.add_argument('-a', '--axis', help='Slicing axis', choices=['x', 'y', 'z'], type=str, default='z')
    parser.add_argument('-p', '--origin-percent', help='Slicing layer (percent)', type=int, default=50)
    parser.add_argument('--commands', help='Comma separated list of inline commands', type=str, default='')

    args = parser.parse_args()


    v = Vis()
    v.open(args.chombo_path)
    v.pseudocolor(args.var, scaling=args.scaling, zmin=args.min, zmax=args.max,
        ct=args.colortable, invert_ct=args.invert)
    v.slice(origin_type='Percent', origin_percent=args.origin_percent, axis_type=args.axis)
    v.draw()
    v.reset_view()

    combs = InlineCombination(v.current_cycle(), v.ncycles())

    combs.mode('p', 'Plot mode')
    combs.action('p', 'd', 'Draw', 'pd', lambda v, _: v.redraw())
    combs.action('p', 's', 'Change scaling', 'pslinear', lambda v, s: v.redraw(scaling=str(s)))
    combs.action('p', 'v', 'Change variable', 'pve_tot', lambda o, v: o.redraw(variable=str(v)))
    combs.action('p', 'u', 'Set range upper bound', 'pu3.14e5', lambda v, u: v.redraw(zmax=float(u)))
    combs.action('p', 'l', 'Set range lower bound', 'pl3.14e5', lambda v, l: v.redraw(zmin=float(l)))

    combs.mode('s', 'Slice mode')
    combs.action('s', 'l', 'Change layer (%)', 'sl25', lambda v, l: v.redraw(origin_percent=int(l)))
    combs.action('s', 'a', 'Change axis', 'say', lambda v, a: v.redraw(axis_type=str(a)))


    if len(args.commands) > 0:
        commands = args.commands.replace(' ', '').split(',')
        for command in commands:
            self.handle(v, command)


    combs.wait(v)


if __name__ == '__main__':
    main()
